# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_end.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 823)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"border-color: rgb(119, 118, 123);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"border-color: rgb(119, 118, 123);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_stopWarning = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stopWarning.sizePolicy().hasHeightForWidth())
        self.pushButton_stopWarning.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        font.setBold(True)
        
        self.pushButton_stopWarning.setFont(font)
        self.pushButton_stopWarning.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 216, 255); /* 浅灰色 */\n"
"    border: 1px solid #d4d4d4; /* 灰色边框 */\n"
"    border-radius: 8px; /* 圆角 */\n"
"    padding: 5px 10px; /* 内边距 */\n"
"    color: rgb(226, 0, 0); /* 按钮文字颜色 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 242, 255); /* 鼠标悬停时变亮 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(157, 178, 255); /* 按下时颜色变深 */\n"
"}")
        self.pushButton_stopWarning.setObjectName("pushButton_stopWarning")
        self.horizontalLayout_4.addWidget(self.pushButton_stopWarning)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_stopWarning_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stopWarning_2.sizePolicy().hasHeightForWidth())
        self.pushButton_stopWarning_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        font.setBold(True)
        
        self.pushButton_stopWarning_2.setFont(font)
        self.pushButton_stopWarning_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 216, 255); /* 浅灰色 */\n"
"    border: 1px solid #d4d4d4; /* 灰色边框 */\n"
"    border-radius: 8px; /* 圆角 */\n"
"    padding: 5px 10px; /* 内边距 */\n"
"    color: rgb(226, 0, 0); /* 按钮文字颜色 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 242, 255); /* 鼠标悬停时变亮 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(157, 178, 255); /* 按下时颜色变深 */\n"
"}")
        self.pushButton_stopWarning_2.setObjectName("pushButton_stopWarning_2")
        self.horizontalLayout_4.addWidget(self.pushButton_stopWarning_2)
        spacerItem2 = QtWidgets.QSpacerItem(13, 33, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_outputExcel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_outputExcel.sizePolicy().hasHeightForWidth())
        self.pushButton_outputExcel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(True)
        
        self.pushButton_outputExcel.setFont(font)
        self.pushButton_outputExcel.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 216, 255); /* 浅灰色 */\n"
"    border: 1px solid #d4d4d4; /* 灰色边框 */\n"
"    border-radius: 8px; /* 圆角 */\n"
"    padding: 5px 10px; /* 内边距 */\n"
"    color: rgb(10, 0, 0); /* 按钮文字颜色 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 242, 255); /* 鼠标悬停时变亮 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(157, 178, 255); /* 按下时颜色变深 */\n"
"}")
        self.pushButton_outputExcel.setObjectName("pushButton_outputExcel")
        self.horizontalLayout_4.addWidget(self.pushButton_outputExcel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(True)
        
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 216, 255); /* 浅灰色 */\n"
"    border: 1px solid #d4d4d4; /* 灰色边框 */\n"
"    border-radius: 8px; /* 圆角 */\n"
"    padding: 5px 10px; /* 内边距 */\n"
"    color: rgb(10, 0, 0); /* 按钮文字颜色 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 242, 255); /* 鼠标悬停时变亮 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(157, 178, 255); /* 按下时颜色变深 */\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_4.addWidget(self.pushButton_clear)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 6)
        self.horizontalLayout_4.setStretch(2, 2)
        self.horizontalLayout_4.setStretch(3, 6)
        self.horizontalLayout_4.setStretch(4, 2)
        self.horizontalLayout_4.setStretch(5, 6)
        self.horizontalLayout_4.setStretch(6, 2)
        self.horizontalLayout_4.setStretch(7, 6)
        self.horizontalLayout_4.setStretch(8, 8)
        self.horizontalLayout_4.setStretch(9, 6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_display = QtWidgets.QLabel(self.centralwidget)
        self.label_display.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_display.setText("")
        self.label_display.setObjectName("label_display")
        self.verticalLayout.addWidget(self.label_display)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        
        self.groupBox_1.setFont(font)
        self.groupBox_1.setObjectName("groupBox_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_setting = QtWidgets.QPushButton(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setting.sizePolicy().hasHeightForWidth())
        self.pushButton_setting.setSizePolicy(sizePolicy)
        self.pushButton_setting.setStyleSheet("QPushButton{\n"
"    image: url(:/images/icons/setting.png);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(200, 200, 200,0);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}url(:/images/icons/setting.png)")
        self.pushButton_setting.setText("")
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.horizontalLayout_3.addWidget(self.pushButton_setting)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout.addWidget(self.groupBox_1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_cam = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cam.sizePolicy().hasHeightForWidth())
        self.pushButton_cam.setSizePolicy(sizePolicy)
        self.pushButton_cam.setStyleSheet("QPushButton{\n"
"    image: url(:/images/icons/camera_on.png);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(200, 200, 200,0);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{\n"
"                     image: url(:/images/icons/camera_off.png);\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}url(:/images/icons/camera_on.png)")
        self.pushButton_cam.setText("")
        self.pushButton_cam.setObjectName("pushButton_cam")
        self.horizontalLayout_5.addWidget(self.pushButton_cam)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinBox_focus = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_focus.sizePolicy().hasHeightForWidth())
        self.spinBox_focus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.spinBox_focus.setFont(font)
        self.spinBox_focus.setStyleSheet("QSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 24px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;\n"
"padding-right: 10px;}\n"
"\n"
"QSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"QSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"\n"
"QSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"QSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"\n"
"QAbstractSpinBox::up-button { subcontrol-origin: border; }\n"
"QAbstractSpinBox::down-button { subcontrol-origin: border; }")
        self.spinBox_focus.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_focus.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_focus.setMinimum(0)
        self.spinBox_focus.setMaximum(1000)
        self.spinBox_focus.setProperty("value", 100)
        self.spinBox_focus.setObjectName("spinBox_focus")
        self.horizontalLayout_6.addWidget(self.spinBox_focus)
        self.horizontalSlider_focus = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_focus.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/images/icons/point.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: #d9d9d9; \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: #373737;                     \n"
"}")
        self.horizontalSlider_focus.setMinimum(0)
        self.horizontalSlider_focus.setMaximum(1000)
        self.horizontalSlider_focus.setProperty("value", 100)
        self.horizontalSlider_focus.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_focus.setObjectName("horizontalSlider_focus")
        self.horizontalLayout_6.addWidget(self.horizontalSlider_focus)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 40)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_display_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_display_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_display_2.setText("")
        self.label_display_2.setObjectName("label_display_2")
        self.verticalLayout_2.addWidget(self.label_display_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    /* background: #f0f0f0; 设置默认状态下的背景颜色 */\n"
"    border: 1px solid #C2C7CB; /* 设置边框颜色 */\n"
"    border-bottom-color: #828282; /* 设置底部边框颜色 */\n"
"    min-width: 10ex; /* 最小宽度 */\n"
"    padding: 5px; /* 内边距 */\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"     background: #e0e0e0; /* 设置选中或悬停状态下的背景颜色 */\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: #e0e0e0; /* 设置选中状态下的背景颜色 */\n"
"    border-color: #828282; /* 选中时的边框颜色 */\n"
"    border-bottom-color: #fff; /* 底部边框颜色 */\n"
"    margin-bottom: 0px; /* 调整底部间距以产生凸起效果 */\n"
"}\n"
"")
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab.setObjectName("tab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget_results = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_results.sizePolicy().hasHeightForWidth())
        self.tableWidget_results.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_results.setFont(font)
        self.tableWidget_results.setAutoFillBackground(True)
        self.tableWidget_results.setStyleSheet("")
        self.tableWidget_results.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_results.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_results.setAutoScroll(True)
        self.tableWidget_results.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_results.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_results.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_results.setObjectName("tableWidget_results")
        self.tableWidget_results.setColumnCount(4)
        self.tableWidget_results.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        
        item.setFont(font)
        self.tableWidget_results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        
        item.setFont(font)
        self.tableWidget_results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        
        item.setFont(font)
        self.tableWidget_results.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        
        item.setFont(font)
        self.tableWidget_results.setHorizontalHeaderItem(3, item)
        self.tableWidget_results.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_results.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget_results.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_results.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_results.verticalHeader().setVisible(False)
        self.tableWidget_results.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_9.addWidget(self.tableWidget_results)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableWidget_ignore = QtWidgets.QTableWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_ignore.sizePolicy().hasHeightForWidth())
        self.tableWidget_ignore.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_ignore.setFont(font)
        self.tableWidget_ignore.setAutoFillBackground(True)
        self.tableWidget_ignore.setStyleSheet("")
        self.tableWidget_ignore.setLineWidth(6)
        self.tableWidget_ignore.setMidLineWidth(1)
        self.tableWidget_ignore.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_ignore.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_ignore.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_ignore.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_ignore.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_ignore.setObjectName("tableWidget_ignore")
        self.tableWidget_ignore.setColumnCount(4)
        self.tableWidget_ignore.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        
        item.setFont(font)
        self.tableWidget_ignore.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        
        item.setFont(font)
        self.tableWidget_ignore.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        
        item.setFont(font)
        self.tableWidget_ignore.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        
        item.setFont(font)
        self.tableWidget_ignore.setHorizontalHeaderItem(3, item)
        self.tableWidget_ignore.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_ignore.horizontalHeader().setDefaultSectionSize(91)
        self.tableWidget_ignore.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_ignore.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_ignore.verticalHeader().setVisible(False)
        self.horizontalLayout_8.addWidget(self.tableWidget_ignore)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_2.setStretch(0, 7)
        self.verticalLayout_2.setStretch(1, 6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 10)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1217, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        
        self.menuBar.setFont(font)
        self.menuBar.setStyleSheet("QMenu {\n"
"background-color:rgba(17,24,47,1);\n"
"border:1px solid rgba(82,130,164,1);\n"
"}\n"
"QMenu::item {\n"
"min-width:50px;\n"
"font-size: 12px;\n"
"color: rgb(225,225,225);\n"
"background:rgba(75,120,154,0.5);\n"
"border:1px solid rgba(82,130,164,1);\n"
"padding:1px 1px;\n"
"margin:1px 1px;}\n"
"QMenu::item:selected {\n"
"background:rgba(82,130,164,1);\n"
"border:1px solid rgba(82,130,164,1);\n"
"}  /*选中或者说鼠标滑过状态*/\\\n"
"QMenu::item:pressed {\n"
"background:rgba(82,130,164,0.4);\n"
"border:1px solid rgba(82,130,164,1);/*摁下状态*/\n"
"}\n"
"")
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        
        self.menu.setFont(font)
        self.menu.setStyleSheet("QMenu::item {\n"
"min-width:50px;\n"
"font-size: 20px;\n"
"color: rgb(225,225,225);\n"
"background:rgba(75,120,154,0.5);\n"
"border:1px solid rgba(82,130,164,1);\n"
"padding:1px 1px;\n"
"margin:1px 1px;}\n"
"QMenu::item:selected {\n"
"background:rgba(82,130,164,1);\n"
"border:1px solid rgba(82,130,164,1);\n"
"}  /*选中或者说鼠标滑过状态*/\\\n"
"QMenu::item:pressed {\n"
"background:rgba(82,130,164,0.4);\n"
"border:1px solid rgba(82,130,164,1);/*摁下状态*/\n"
"}\n"
"")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.menu_sizeCalibration = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.menu_sizeCalibration.setFont(font)
        self.menu_sizeCalibration.setObjectName("menu_sizeCalibration")
        self.menu.addAction(self.menu_sizeCalibration)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "水下检测"))
        self.pushButton_stopWarning.setText(_translate("MainWindow", "停止报警"))
        self.pushButton_stopWarning_2.setText(_translate("MainWindow", "挂起"))
        self.pushButton_outputExcel.setText(_translate("MainWindow", "异常清单导出"))
        self.pushButton_clear.setText(_translate("MainWindow", "一键清空屏蔽"))
        self.label.setText(_translate("MainWindow", "NG"))
        self.groupBox_1.setTitle(_translate("MainWindow", "设置"))
        self.groupBox_3.setTitle(_translate("MainWindow", "输入"))
        self.groupBox_5.setTitle(_translate("MainWindow", "焦距"))
        item = self.tableWidget_results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tableWidget_results.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类别"))
        item = self.tableWidget_results.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "置信度"))
        item = self.tableWidget_results.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "时间"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "缺陷序列"))
        item = self.tableWidget_ignore.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tableWidget_ignore.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "屏蔽类别"))
        item = self.tableWidget_ignore.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "坐标"))
        item = self.tableWidget_ignore.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "屏蔽时间"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "屏蔽区域"))
        self.menu.setTitle(_translate("MainWindow", "功能"))
        self.menu_sizeCalibration.setText(_translate("MainWindow", "尺寸标定"))
from src.ui import apprcc
