# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu1(object):
    def setupUi(self, Menu1):
        Menu1.setObjectName("Menu1")
        Menu1.resize(950, 850)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Menu1.setWindowIcon(icon)
        Menu1.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"border-color: rgb(119, 118, 123);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Menu1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(Menu1)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        font.setBold(True)
        
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_showPicture = QtWidgets.QLabel(Menu1)
        self.label_showPicture.setStyleSheet("background:rgb(0, 0, 0)")
        self.label_showPicture.setText("")
        self.label_showPicture.setObjectName("label_showPicture")
        self.verticalLayout.addWidget(self.label_showPicture)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(Menu1)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        font.setBold(True)
        
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_lengthPixel = QtWidgets.QLabel(Menu1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lengthPixel.sizePolicy().hasHeightForWidth())
        self.label_lengthPixel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_lengthPixel.setFont(font)
        self.label_lengthPixel.setStyleSheet("background:rgb(144, 144, 144);")
        self.label_lengthPixel.setText("")
        self.label_lengthPixel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lengthPixel.setObjectName("label_lengthPixel")
        self.horizontalLayout_3.addWidget(self.label_lengthPixel)
        self.label_2 = QtWidgets.QLabel(Menu1)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        font.setBold(True)
        
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Menu1)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        font.setBold(True)
        
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Menu1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"font-size: 24px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;\n"
"padding-right: 10px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"\n"
"QAbstractSpinBox::up-button { subcontrol-origin: border; }\n"
"QAbstractSpinBox::down-button { subcontrol-origin: border; }")
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setMaximum(99999.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox)
        self.comboBox = QtWidgets.QComboBox(Menu1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setStyleSheet("background:rgb(255, 255, 255);\n"
"font-weight:bold;")
        self.comboBox.setEditable(True)
        self.comboBox.setPlaceholderText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 8)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 10)
        self.horizontalLayout_5.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(Menu1)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        font.setBold(True)
        
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.label_scale = QtWidgets.QLabel(Menu1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_scale.sizePolicy().hasHeightForWidth())
        self.label_scale.setSizePolicy(sizePolicy)
        self.label_scale.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_scale.setFont(font)
        self.label_scale.setStyleSheet("background:rgb(144, 144, 144);")
        self.label_scale.setText("")
        self.label_scale.setAlignment(QtCore.Qt.AlignCenter)
        self.label_scale.setObjectName("label_scale")
        self.horizontalLayout_6.addWidget(self.label_scale)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.pushButton_loadPicture = QtWidgets.QPushButton(Menu1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loadPicture.sizePolicy().hasHeightForWidth())
        self.pushButton_loadPicture.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(18)
        font.setBold(True)
        
        self.pushButton_loadPicture.setFont(font)
        self.pushButton_loadPicture.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 216, 255); /* 浅灰色 */\n"
"    border: 1px solid #d4d4d4; /* 灰色边框 */\n"
"    border-radius: 8px; /* 圆角 */\n"
"    padding: 5px 10px; /* 内边距 */\n"
"    color: #333; /* 按钮文字颜色 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 242, 255); /* 鼠标悬停时变亮 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(157, 178, 255); /* 按下时颜色变深 */\n"
"}")
        self.pushButton_loadPicture.setObjectName("pushButton_loadPicture")
        self.horizontalLayout_7.addWidget(self.pushButton_loadPicture)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.pushButton_calibration = QtWidgets.QPushButton(Menu1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_calibration.sizePolicy().hasHeightForWidth())
        self.pushButton_calibration.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(18)
        font.setBold(True)
        
        self.pushButton_calibration.setFont(font)
        self.pushButton_calibration.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 216, 255); /* 浅灰色 */\n"
"    border: 1px solid #d4d4d4; /* 灰色边框 */\n"
"    border-radius: 8px; /* 圆角 */\n"
"    padding: 5px 10px; /* 内边距 */\n"
"    color: #333; /* 按钮文字颜色 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 242, 255); /* 鼠标悬停时变亮 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(157, 178, 255); /* 按下时颜色变深 */\n"
"}")
        self.pushButton_calibration.setObjectName("pushButton_calibration")
        self.horizontalLayout_7.addWidget(self.pushButton_calibration)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 6)
        self.horizontalLayout_7.setStretch(2, 1)
        self.horizontalLayout_7.setStretch(3, 6)
        self.horizontalLayout_7.setStretch(4, 1)
        self.horizontalLayout_7.setStretch(5, 6)
        self.horizontalLayout_7.setStretch(6, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 20)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 2)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 4)
        self.verticalLayout_2.setStretch(6, 4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Menu1)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Menu1)

    def retranslateUi(self, Menu1):
        _translate = QtCore.QCoreApplication.translate
        Menu1.setWindowTitle(_translate("Menu1", "尺寸标定"))
        self.label_6.setText(_translate("Menu1", "识别到的圆 ："))
        self.label.setText(_translate("Menu1", "圆直径的像素长度 ："))
        self.label_2.setText(_translate("Menu1", "像素"))
        self.label_3.setText(_translate("Menu1", "圆直径的实际长度 ："))
        self.comboBox.setCurrentText(_translate("Menu1", "mm"))
        self.comboBox.setItemText(0, _translate("Menu1", "mm"))
        self.comboBox.setItemText(1, _translate("Menu1", "cm"))
        self.comboBox.setItemText(2, _translate("Menu1", "m"))
        self.label_4.setText(_translate("Menu1", "比例尺 ："))
        self.pushButton_loadPicture.setText(_translate("Menu1", "加载图片"))
        self.pushButton_calibration.setText(_translate("Menu1", "标定"))
from src.ui import apprcc
