# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1094, 769)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"border-color: rgb(119, 118, 123);")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox QAbstractItemView {\n"
"font-size: 16px;\n"
"outline:none;\n"
"border:none;}\n"
"\n"
"QComboBox{\n"
"font-size: 20px;\n"
"min-height:1.5em;\n"
"color: rgb(218, 218, 218);\n"
"border-width:0px;\n"
"border-color:white;\n"
"border-style:solid;\n"
"background-color: rgba(200, 200, 200,50);}\n"
"\n"
"QComboBox::drop-down {\n"
"margin-top:1;\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgba(200, 200, 200,50);\n"
"border-image: url(:/images/icons/roll_down.png);\n"
"}\n"
"\n"
"QComboBox::disabled{\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(375, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.groupBox_8 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_timeForStartWarning = QtWidgets.QSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_timeForStartWarning.sizePolicy().hasHeightForWidth())
        self.spinBox_timeForStartWarning.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.spinBox_timeForStartWarning.setFont(font)
        self.spinBox_timeForStartWarning.setStyleSheet("QSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 24px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;\n"
"padding-right: 10px;}\n"
"\n"
"QSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"QSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"\n"
"QSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"QSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"\n"
"QAbstractSpinBox::up-button { subcontrol-origin: border; }\n"
"QAbstractSpinBox::down-button { subcontrol-origin: border; }")
        self.spinBox_timeForStartWarning.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_timeForStartWarning.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_timeForStartWarning.setMinimum(0)
        self.spinBox_timeForStartWarning.setMaximum(100)
        self.spinBox_timeForStartWarning.setProperty("value", 1)
        self.spinBox_timeForStartWarning.setObjectName("spinBox_timeForStartWarning")
        self.horizontalLayout.addWidget(self.spinBox_timeForStartWarning)
        self.horizontalLayout.setStretch(0, 10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_timeForStopWarning = QtWidgets.QSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_timeForStopWarning.sizePolicy().hasHeightForWidth())
        self.spinBox_timeForStopWarning.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.spinBox_timeForStopWarning.setFont(font)
        self.spinBox_timeForStopWarning.setStyleSheet("QSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 24px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;\n"
"padding-right: 10px;}\n"
"\n"
"QSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"QSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"\n"
"QSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"QSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"\n"
"QAbstractSpinBox::up-button { subcontrol-origin: border; }\n"
"QAbstractSpinBox::down-button { subcontrol-origin: border; }")
        self.spinBox_timeForStopWarning.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_timeForStopWarning.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_timeForStopWarning.setMinimum(0)
        self.spinBox_timeForStopWarning.setMaximum(100)
        self.spinBox_timeForStopWarning.setProperty("value", 3)
        self.spinBox_timeForStopWarning.setObjectName("spinBox_timeForStopWarning")
        self.horizontalLayout_2.addWidget(self.spinBox_timeForStopWarning)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_savePictureInterval = QtWidgets.QSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_savePictureInterval.sizePolicy().hasHeightForWidth())
        self.spinBox_savePictureInterval.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.spinBox_savePictureInterval.setFont(font)
        self.spinBox_savePictureInterval.setStyleSheet("QSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 24px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;\n"
"padding-right: 10px;}\n"
"\n"
"QSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"QSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"\n"
"QSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"QSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"\n"
"QAbstractSpinBox::up-button { subcontrol-origin: border; }\n"
"QAbstractSpinBox::down-button { subcontrol-origin: border; }")
        self.spinBox_savePictureInterval.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_savePictureInterval.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_savePictureInterval.setMinimum(0)
        self.spinBox_savePictureInterval.setMaximum(100)
        self.spinBox_savePictureInterval.setProperty("value", 3)
        self.spinBox_savePictureInterval.setObjectName("spinBox_savePictureInterval")
        self.horizontalLayout_3.addWidget(self.spinBox_savePictureInterval)
        self.horizontalLayout_3.setStretch(0, 10)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.spinBox_timeForObjectIntervalTime = QtWidgets.QSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_timeForObjectIntervalTime.sizePolicy().hasHeightForWidth())
        self.spinBox_timeForObjectIntervalTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.spinBox_timeForObjectIntervalTime.setFont(font)
        self.spinBox_timeForObjectIntervalTime.setStyleSheet("QSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 24px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;\n"
"padding-right: 10px;}\n"
"\n"
"QSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"QSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"\n"
"QSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"QSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"\n"
"QAbstractSpinBox::up-button { subcontrol-origin: border; }\n"
"QAbstractSpinBox::down-button { subcontrol-origin: border; }")
        self.spinBox_timeForObjectIntervalTime.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_timeForObjectIntervalTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_timeForObjectIntervalTime.setMinimum(0)
        self.spinBox_timeForObjectIntervalTime.setMaximum(1000)
        self.spinBox_timeForObjectIntervalTime.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBox_timeForObjectIntervalTime.setProperty("value", 20)
        self.spinBox_timeForObjectIntervalTime.setObjectName("spinBox_timeForObjectIntervalTime")
        self.horizontalLayout_9.addWidget(self.spinBox_timeForObjectIntervalTime)
        self.horizontalLayout_9.setStretch(0, 10)
        self.horizontalLayout_9.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.spinBox_vortexMinSize = QtWidgets.QSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_vortexMinSize.sizePolicy().hasHeightForWidth())
        self.spinBox_vortexMinSize.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.spinBox_vortexMinSize.setFont(font)
        self.spinBox_vortexMinSize.setStyleSheet("QSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 24px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;\n"
"padding-right: 10px;}\n"
"\n"
"QSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"QSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"\n"
"QSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"QSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"\n"
"QAbstractSpinBox::up-button { subcontrol-origin: border; }\n"
"QAbstractSpinBox::down-button { subcontrol-origin: border; }")
        self.spinBox_vortexMinSize.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_vortexMinSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_vortexMinSize.setMinimum(0)
        self.spinBox_vortexMinSize.setMaximum(1000)
        self.spinBox_vortexMinSize.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBox_vortexMinSize.setProperty("value", 0)
        self.spinBox_vortexMinSize.setObjectName("spinBox_vortexMinSize")
        self.horizontalLayout_12.addWidget(self.spinBox_vortexMinSize)
        self.horizontalLayout_12.setStretch(0, 10)
        self.horizontalLayout_12.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 10)
        self.verticalLayout.setStretch(3, 10)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_setDefault = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setDefault.sizePolicy().hasHeightForWidth())
        self.pushButton_setDefault.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        
        self.pushButton_setDefault.setFont(font)
        self.pushButton_setDefault.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 216, 255); /* 浅灰色 */\n"
"    border: 1px solid #d4d4d4; /* 灰色边框 */\n"
"    border-radius: 8px; /* 圆角 */\n"
"    padding: 5px 10px; /* 内边距 */\n"
"    color: #333; /* 按钮文字颜色 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 242, 255); /* 鼠标悬停时变亮 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(157, 178, 255); /* 按下时颜色变深 */\n"
"}")
        self.pushButton_setDefault.setObjectName("pushButton_setDefault")
        self.horizontalLayout_5.addWidget(self.pushButton_setDefault)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pushButton_setPara = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setPara.sizePolicy().hasHeightForWidth())
        self.pushButton_setPara.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        
        self.pushButton_setPara.setFont(font)
        self.pushButton_setPara.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 216, 255); /* 浅灰色 */\n"
"    border: 1px solid #d4d4d4; /* 灰色边框 */\n"
"    border-radius: 8px; /* 圆角 */\n"
"    padding: 5px 10px; /* 内边距 */\n"
"    color: #333; /* 按钮文字颜色 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 242, 255); /* 鼠标悬停时变亮 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(157, 178, 255); /* 按下时颜色变深 */\n"
"}")
        self.pushButton_setPara.setObjectName("pushButton_setPara")
        self.horizontalLayout_5.addWidget(self.pushButton_setPara)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 3)
        self.horizontalLayout_5.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.verticalLayout_4.setStretch(0, 10)
        self.verticalLayout_4.setStretch(1, 10)
        self.verticalLayout_4.setStretch(2, 30)
        self.verticalLayout_4.setStretch(3, 10)
        self.verticalLayout_4.setStretch(4, 10)
        self.verticalLayout_4.setStretch(5, 10)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_9 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_startWarning = QtWidgets.QRadioButton(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_startWarning.setFont(font)
        self.radioButton_startWarning.setAutoExclusive(False)
        self.radioButton_startWarning.setObjectName("radioButton_startWarning")
        self.horizontalLayout_4.addWidget(self.radioButton_startWarning)
        self.radioButton_startSavePicture = QtWidgets.QRadioButton(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_startSavePicture.setFont(font)
        self.radioButton_startSavePicture.setObjectName("radioButton_startSavePicture")
        self.horizontalLayout_4.addWidget(self.radioButton_startSavePicture)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.doubleSpinBox_conf = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_conf.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 24px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;\n"
"padding-right: 10px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"\n"
"QAbstractSpinBox::up-button { subcontrol-origin: border; }\n"
"QAbstractSpinBox::down-button { subcontrol-origin: border; }")
        self.doubleSpinBox_conf.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_conf.setMaximum(1.0)
        self.doubleSpinBox_conf.setSingleStep(0.01)
        self.doubleSpinBox_conf.setProperty("value", 0.35)
        self.doubleSpinBox_conf.setObjectName("doubleSpinBox_conf")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_conf)
        self.horizontalSlider_conf = QtWidgets.QSlider(self.groupBox_6)
        self.horizontalSlider_conf.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/images/icons/point.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: #d9d9d9; \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: #373737;                     \n"
"}")
        self.horizontalSlider_conf.setMinimum(0)
        self.horizontalSlider_conf.setMaximum(100)
        self.horizontalSlider_conf.setSingleStep(1)
        self.horizontalSlider_conf.setPageStep(100)
        self.horizontalSlider_conf.setProperty("value", 35)
        self.horizontalSlider_conf.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_conf.setObjectName("horizontalSlider_conf")
        self.horizontalLayout_7.addWidget(self.horizontalSlider_conf)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.groupBox_7 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.doubleSpinBox_iou = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_iou.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 24px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;\n"
"padding-right: 10px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"\n"
"QAbstractSpinBox::up-button { subcontrol-origin: border; }\n"
"QAbstractSpinBox::down-button { subcontrol-origin: border; }")
        self.doubleSpinBox_iou.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_iou.setMaximum(1.0)
        self.doubleSpinBox_iou.setSingleStep(0.1)
        self.doubleSpinBox_iou.setProperty("value", 0.45)
        self.doubleSpinBox_iou.setObjectName("doubleSpinBox_iou")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_iou)
        self.horizontalSlider_iou = QtWidgets.QSlider(self.groupBox_7)
        self.horizontalSlider_iou.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/images/icons/point.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: #d9d9d9; \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: #373737;                     \n"
"}")
        self.horizontalSlider_iou.setMinimum(0)
        self.horizontalSlider_iou.setMaximum(100)
        self.horizontalSlider_iou.setSingleStep(1)
        self.horizontalSlider_iou.setProperty("value", 45)
        self.horizontalSlider_iou.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_iou.setObjectName("horizontalSlider_iou")
        self.horizontalLayout_8.addWidget(self.horizontalSlider_iou)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinBox_interval = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_interval.sizePolicy().hasHeightForWidth())
        self.spinBox_interval.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.spinBox_interval.setFont(font)
        self.spinBox_interval.setStyleSheet("QSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 24px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;\n"
"padding-right: 10px;}\n"
"\n"
"QSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"QSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_down.png);}\n"
"\n"
"QSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"QSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/images/icons/botton_up.png);}\n"
"\n"
"QAbstractSpinBox::up-button { subcontrol-origin: border; }\n"
"QAbstractSpinBox::down-button { subcontrol-origin: border; }")
        self.spinBox_interval.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_interval.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_interval.setMinimum(0)
        self.spinBox_interval.setMaximum(200)
        self.spinBox_interval.setProperty("value", 50)
        self.spinBox_interval.setObjectName("spinBox_interval")
        self.horizontalLayout_6.addWidget(self.spinBox_interval)
        self.horizontalSlider_interval = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_interval.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/images/icons/point.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: #d9d9d9; \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: #373737;                     \n"
"}")
        self.horizontalSlider_interval.setMinimum(0)
        self.horizontalSlider_interval.setMaximum(200)
        self.horizontalSlider_interval.setProperty("value", 50)
        self.horizontalSlider_interval.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_interval.setObjectName("horizontalSlider_interval")
        self.horizontalLayout_6.addWidget(self.horizontalSlider_interval)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.verticalLayout_5.setStretch(0, 5)
        self.verticalLayout_5.setStretch(1, 2)
        self.verticalLayout_5.setStretch(2, 5)
        self.verticalLayout_5.setStretch(3, 2)
        self.verticalLayout_5.setStretch(4, 5)
        self.verticalLayout_5.setStretch(5, 2)
        self.verticalLayout_5.setStretch(6, 5)
        self.verticalLayout_5.setStretch(7, 2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.horizontalLayout_10.setStretch(0, 10)
        self.horizontalLayout_10.setStretch(2, 10)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "设置"))
        self.groupBox_4.setTitle(_translate("Dialog", "模式选择"))
        self.comboBox.setItemText(0, _translate("Dialog", "仅保存图片"))
        self.comboBox.setItemText(1, _translate("Dialog", "仅检测"))
        self.comboBox.setItemText(2, _translate("Dialog", "检测+保存图片"))
        self.comboBox.setItemText(3, _translate("Dialog", "无"))
        self.label_4.setText(_translate("Dialog", "注：打开或者取消检测模式需重启程序才会生效"))
        self.groupBox_8.setTitle(_translate("Dialog", "参数设置"))
        self.label.setText(_translate("Dialog", "检测到异常情况持续多少秒开始报警："))
        self.label_2.setText(_translate("Dialog", "异常情况消失多少秒后停止报警：    "))
        self.label_3.setText(_translate("Dialog", "启用保存图片模式时保存的间隔时间："))
        self.label_5.setText(_translate("Dialog", "多少秒内出现同一缺陷算一次异常："))
        self.label_6.setText(_translate("Dialog", "检测的旋涡尺寸的大小大于多少毫米时会被记录："))
        self.pushButton_setDefault.setText(_translate("Dialog", "恢复默认"))
        self.pushButton_setPara.setText(_translate("Dialog", "设置参数"))
        self.groupBox_9.setTitle(_translate("Dialog", "功能设置"))
        self.radioButton_startWarning.setText(_translate("Dialog", "启用报警"))
        self.radioButton_startSavePicture.setText(_translate("Dialog", "启用保存视频"))
        self.groupBox_6.setTitle(_translate("Dialog", "置信度"))
        self.groupBox_7.setTitle(_translate("Dialog", "交并比"))
        self.groupBox_5.setTitle(_translate("Dialog", "检测时间间隔"))
from src.ui import apprcc
